Test getting of files changed in a PR

diff --git a/eng/pipelines/templates/jobs/archetype-sdk-client.yml b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
--- a/eng/pipelines/templates/jobs/archetype-sdk-client.yml
+++ b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
@@ -1,67 +1,41 @@
 jobs:
-  - job: Build
-    variables:
-      - template: ../variables/globals.yml
-    pool:
-      vmImage: windows-2019
-    steps:
-      - pwsh: |
-          echo "##vso[build.addbuildtag]Scheduled"
-        displayName: "Tag scheduled builds"
-        condition: and(eq(variables['Build.SourceBranchName'],'master'),eq(variables['Build.Reason'],'Schedule'))
-      - template: /eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
-      - pwsh: |
-          $skipDevBuildNumber = "false"
-          # For .NET builds the only case we want to not have dev build numbers on our packages is when it is manually queued and
-          # the SetDevVersion property isn't set to true. All other cases should contain dev version numbers.
-          if ('$(Build.Reason)' -eq 'Manual' -and '$(SetDevVersion)' -ne 'true') {
-            $skipDevBuildNumber = "true"
-          }
-          $versioningProperties = "/p:OfficialBuildId=$(OfficialBuildId) /p:SkipDevBuildNumber=$skipDevBuildNumber";
-          echo "##vso[task.setvariable variable=VersioningProperties]$versioningProperties"
-        displayName: "Setup .NET specific versioning properties"
-      - task: UsePythonVersion@0
-        displayName: 'Use Python 3.6'
-        inputs:
-          versionSpec: '3.6'
-      - template: /eng/common/pipelines/templates/steps/replace-relative-links.yml
-        parameters:
-          TargetFolder: '.'
-          RootFolder: '.'
-          BuildSHA: $(Build.SourceVersion)
-          RepoId: 'Azure/azure-sdk-for-net'
-      - task: UseDotNet@2
-        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
-        inputs:
-          version: "$(DotNetCoreSDKVersion)"
-      - script: >-
-          dotnet pack eng/service.proj -o $(Build.ArtifactStagingDirectory) -warnaserror /p:ServiceDirectory=${{parameters.ServiceToBuild}}
-          /p:PublicSign=false $(VersioningProperties) /p:Configuration=$(BuildConfiguration) /p:CommitSHA=$(Build.SourceVersion)
-        displayName: "Build and Package"
-        env:
-          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
-          DOTNET_CLI_TELEMETRY_OPTOUT: 1
-          DOTNET_MULTILEVEL_LOOKUP: 0
-      - task: PublishPipelineArtifact@1
-        condition: succeeded()
-        inputs:
-          artifactName: packages
-          path: $(Build.ArtifactStagingDirectory)
-      - template: ../steps/archetype-sdk-docs.yml
-        parameters:
-          ServiceDirectory: ${{parameters.ServiceDirectory}}
-          Artifacts: ${{parameters.Artifacts}}
-          DocGenerationDir: "$(Build.SourcesDirectory)/doc/ApiDocGeneration"
-          LibType: 'client'
   - job: "Analyze"
     condition: ne(variables['Skip.Analyze'], true)
     variables:
       - template: ../variables/globals.yml
-    dependsOn:
-      - Build
     pool:
       vmImage: "windows-2019"
     steps:
+      - pwsh: |
+          Install-Module -Name powershell-yaml -RequiredVersion 0.4.1 -Force -Scope CurrentUser
+          $remoteHEAD = git rev-parse origin/master
+          $localHEAD = git rev-parse HEAD
+          $ymlfilesChanged = (git diff --name-only $remoteHEAD...$localHEAD) | Where-Object {$_ -like '*.yml'}
+          
+          foreach ($file in $ymlfilesChanged)
+          {
+            Write-Host $file
+            $ymlContent = Get-Content "$(Build.SourcesDirectory)/$file" -Raw
+            $ymlObject = ConvertFrom-Yaml $ymlContent -Ordered
+
+            if ($ymlObject.Contains("resources"))
+            {
+              if ($ymlObject["resources"].Contains("repositories"))
+              {
+                $repositories = $ymlObject["resources"]["repositories"]
+                foreach ($repo in $repositories)
+                {
+                  $repoName = $repo["repository"]
+                  if (-not ($repo.Contains("ref")))
+                  {
+                    Write-Error "Ref not found. Please ensure you add a Ref: when using repository resource"
+                    exit 1
+                  }
+                }
+              }
+            }
+          }
+        displayName: "Test files changed in PR"
       - task: UsePythonVersion@0
         displayName: "Use Python 3.6"
         inputs:
@@ -113,56 +87,3 @@ jobs:
           arguments: -ServiceDirectory ${{parameters.ServiceToBuild}}
           pwsh: true
           failOnStderr:  false
-  - job: "Test"
-    condition: ne(variables['Skip.Test'], true)
-    variables:
-      - template: ../variables/globals.yml
-    strategy:
-      maxParallel: $[ variables['MaxParallelTestJobs'] ]
-      matrix:
-        Linux:
-          OSVmImage: "ubuntu-18.04"
-          TestTargetFramework: netcoreapp2.1
-        Windows_NetCoreApp:
-          OSVmImage: "windows-2019"
-          TestTargetFramework: netcoreapp2.1
-        Windows_NetCoreApp_ProjectReferences:
-          OSVmImage: "windows-2019"
-          TestTargetFramework: netcoreapp2.1
-          ConvertToProjectReferenceOption: /p:UseProjectReferenceToAzureClients=true
-        Windows_NetFramework:
-          OSVmImage: "windows-2019"
-          TestTargetFramework: net461
-        MacOs:
-          OSVmImage: "macOS-10.15"
-          TestTargetFramework: netcoreapp2.1
-    pool:
-      vmImage: "$(OSVmImage)"
-    steps:
-      - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
-      - task: DotNetCoreInstaller@2
-        displayName: "Use .NET Core runtime $(DotNetCoreRuntimeVersion)"
-        inputs:
-          packageType: runtime
-          version: "$(DotNetCoreRuntimeVersion)"
-      - task: DotNetCoreInstaller@2
-        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
-        inputs:
-          packageType: sdk
-          version: "$(DotNetCoreSDKVersion)"
-      - script: >-
-          dotnet test eng/service.proj --filter TestCategory!=Live --framework $(TestTargetFramework) --logger "trx;LogFileName=$(TestTargetFramework).trx" --logger:"console;verbosity=normal"
-          /p:ServiceDirectory=${{parameters.ServiceToBuild}} /p:IncludeSrc=false /p:IncludeSamples=false /p:Configuration=$(BuildConfiguration) $(ConvertToProjectReferenceOption)
-        displayName: "Build & Test ($(TestTargetFramework))"
-        env:
-          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
-          DOTNET_CLI_TELEMETRY_OPTOUT: 1
-          DOTNET_MULTILEVEL_LOOKUP: 0
-      - task: PublishTestResults@2
-        condition: always()
-        displayName: "Publish Results ($(TestTargetFramework))"
-        inputs:
-          testResultsFiles: "**/$(TestTargetFramework)*.trx"
-          testRunTitle: "$(OSName) $(TestTargetFramework)"
-          testResultsFormat: "VSTest"
-          mergeTestResults: true
